# This is a basic workflow to help you get started with Actions

name: createPackage

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  workflow_dispatch:
  
  push:
    branches: [main]
    tags:        
      - release-*

env:
  DEV_HUB_URL: ${{ secrets.DEV_HUB_URL }}
  QA_URL: ${{ secrets.QA_URL }}
  # Allows you to run this workflow manually from the Actions tab

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Create-package-version:
      runs-on: ubuntu-latest
      container : salesforce/salesforcedx:latest-full
      defaults:
        run:
          shell: bash
      steps:
        - uses: actions/checkout@v2
        - run: | 
              echo $DEV_HUB_URL > devHubURLFile
              sfdx force:auth:sfdxurl:store -d -f devHubURLFile
              rm devHubURLFile
              chmod +x ./scripts/createPackage.sh
              ./scripts/createPackage.sh
